# Generated by Django 4.0 on 2024-06-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userregistrationmodel_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationmodel',
            old_name='title',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='email',
            field=models.CharField(default='default@example.com', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='loginid',
            field=models.CharField(default='default_loginid', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
