# Generated by Django 4.0 on 2024-06-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_userregistrationmodel_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
    ]
